### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by Zearin** [crystal/autocode#22]
I am trying autocode for the first time.  

I ran `autocode init`, then added some stuff so that `config.yml` looks like this:

```yaml
name: autocode-docpad-redux-test
version: 8.0.0-pre-alpha
description: ...
copyright: 2015 Zearin
license: mit
imports:
	crystal/crystal-readme: ~0.2.5
	crystal/editorconfig: ~0.1.0
	crystal/coffeescript: ~0.4.0
```

However, when I ran `autocode config`, I get this error:

```
$ autocode config
Configuration failed validation:
[ { message: 'Failed "type" criteria: expecting object, found null',
    context: '#/imports',
    value: null,
    criteria: { type: 'object', additionalProperties: [Object] },
    toString: [Function: errorToString] } ]
Invalid Configuration for path: /Users/amrogers/Developer/Projects/autocode-test
```

I have a vague notion that the issue is somewhere in my `imports` statement, but I have no idea what the issue is.  

Here’s an example error message that I would prefer to see instead:

```
Invalid Configuration for path: /Users/amrogers/Developer/Projects/autocode-test
Configuration failed validation:
    On line 6, `imports` is missing the following properties: 
        - «key1» 
        - «key2»
        - «key3»
```
